config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'battle', to: 'pages#battle'
  resources :pokemons do 
    resources :decks , only: [:new, :create]
  end

  resources :decks, only: [:show, :index, :destroy, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability_validator.rb
class AvailabilityValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    decks = Deck.where(["pokemon_id =?", record.pokemon_id])
    date_ranges = decks.map { |b| b.start_date..b.end_date }

    date_ranges.each do |range|
      if range.include? value
        record.errors.add(attribute, "not available")
      end
    end
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon

  validates :start_date, :end_date, presence: true, availability: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_many :decks
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
    
  def unavailable_dates
    decks.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pokemons
  has_many :decks
  has_many :deck_pokemons, through: :decks, source: :pokemon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
before_action :set_pokemon , only: [:new,:create]

  def index
    @user = current_user
    @decks = Deck.where(user: @user)
  end
  

  def show
    @deck = Deck.find(params[:id])
  end
  
  def new
    @deck = Deck.new
    @deck.pokemon = @pokemon
  end

  def create
    @deck = Deck.new(params_deck)
    @deck.pokemon = @pokemon 
    @deck.user = current_user
      if @deck.save
        flash[:success] = "Deck successfully created"
        redirect_to @deck
      else
        flash[:error] = "Something went wrong"
        render 'new'
      end
  end

  def destroy
    @deck = Deck.find(params[:id])
    if @deck.destroy
      flash[:success] = 'Deck was successfully deleted.'
      redirect_to decks_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to decks_path
    end
  end
  
  
  private

  def check_decks(deck,pokemon)
    pokemon.decks.each do |elem|
      if elem.start.eql?(deck.start)
        return false
      end
    end
  end

  def set_pokemon
    @pokemon = Pokemon.find(params[:pokemon_id])
  end

  def params_deck
    params.require(:deck).permit(:start_date,:end_date, :user_id, :pokemon_id)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    if params[:query].present?
      @pokemons = Pokemon.where(name: params[:query])
    else
      @pokemons = Pokemon.all
    end
  end

  def battle
    @user = current_user
    @pokemons = current_user.deck_pokemons
    @oponent = Pokemon.order('RANDOM()').first
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only:[:index, :show]

  def index
    if params[:query].present?
      @pokemons = Pokemon.where('name ILIKE ?', "%#{params[:query]}%")
    else
    @user = current_user
    @pokemons = Pokemon.where(user: @user)
    end
  end

  def show
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(params_pokemon) 
    @pokemon.user = current_user 
    if @pokemon.save
      redirect_to @pokemon, notice: 'Pokemon was successfully created.'
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @pokemon.update(params_pokemon)
      redirect_to @pokemon, notice: 'Pokemon was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pokemon.destroy
    redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.'
  end
  
  
  
  
  private
  
  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

  def params_pokemon
    params.require(:pokemon).permit(:name,:location,:element,:life,:attack,:photo,:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/decks/index.html.erb
<h1>My Army</h1>
<div class="container">
  <div class="card-columns">
    <% @decks.each do |deck| %>
    <div class="card" style="width: 18rem;">
      <h5 class="card-title text-center"><%= deck.pokemon.name %></h5>

      <div class="card-body">
        <% if deck.pokemon.photo.attached?%>
        <%= cl_image_tag deck.pokemon.photo.key, class:"card-img-top" %>
        <%end%>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Element : <%= deck.pokemon.element %></li>
        <li class="list-group-item">Attack Points : <%= deck.pokemon.attack %></li>
        <li class="list-group-item">Life Points : <%= deck.pokemon.life %></li>
        <li class="list-group-item">Location : <%= deck.pokemon.location %></li>
      </ul>
      <div class="card-body">
        <%= link_to "Remove from Deck", deck_path(deck), method: :delete, class:"btn btn-primary", data: {confirm: "Are you sure"} %>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/decks/new.html.erb
    <h1>Recruit for Army </h1>
    <div class="flex-center mt-4">
      <div class="col-xs-12 col-sm-6">
        <div class="text-center">
          <%= simple_form_for [@pokemon,@deck] do |f| %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.submit %>
          <% end%>

        </div>
      </div>
    </div>

app/views/decks/show.html.erb
<h1> SHOW </h1>
<div class="container">
  <div class="card mx-auto" style="width: 18rem; ">
    <h5 class="card-title text-center" style="margin-top: 8px"><%= @deck.pokemon.name %></h5>

    <div class="card-body">
      <% if @deck.pokemon.photo.attached? %>
      <%= cl_image_tag @deck.pokemon.photo.key, class:"card-img-top" %>
    </div>
    <%end%>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Element : <%= @deck.pokemon.element %></li>
      <li class="list-group-item">Attack Points : <%= @deck.pokemon.attack %> <i class="fas fa-khanda"></i></li>
      <li class="list-group-item">Life Points : <%= @deck.pokemon.life %> <i class="fas fa-heart"></i></li>
      <li class="list-group-item">Location : <%= @deck.pokemon.location %> <i class="fas fa-map-marker-alt"></i></li>
    </ul>
    <div class="card-body mx-auto">
      <%= link_to 'Add to Deck', new_pokemon_deck_path(@deck.pokemon), class: 'btn btn-primary' %> |
      <%= link_to 'Back', pokemons_path, class: 'btn btn-primary'  %>
    </div>
    <div class="card-footer mx-auto">
      <% if user_signed_in? && current_user.eql?(@deck.pokemon.user) %>
      <%= link_to 'Edit', edit_pokemon_path(@deck.pokemon), class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PokemonCombatRoyal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <div class="container">
    <div class="row mt-4">
      <div class="col">
        <%= yield %>
      </div>
    </div>
  </div>
</body>

</html>

app/views/pages/battle.html.erb
<h1>Battle</h1>
<div class="container" style="display: flex; justify-content: space-between; margin-top: 40px">
  <div class="container">
    <h4>My Army</h4>
    <% @pokemons.each do |pokemon| %>
    <div class="card clickable" style="width: 10rem;">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= cl_image_tag pokemon.photo.key, class:"card-img-top" %></li>
      </ul>
    </div>
    <% end %>
  </div>

  <div class="container">
    <h4>Oponent Choice</h4>
    <div class="card" style="width: 10rem;">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= cl_image_tag @oponent.photo.key, class:"card-img-top" %></li>
      </ul>
    </div>
  </div>
  <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalCenter">
    Start Fight
  </button>

  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-center" id="exampleModalLongTitle">THE WINNER IS</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if @oponent.attack > @pokemons.first.attack %>
          <%= cl_image_tag @oponent.photo.key, class:"card-img-top" %>
          <% else %>
          <%= cl_image_tag @pokemons.first.photo.key, class:"card-img-top" %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pokemons</h1>
<div class="container">
  <div class="card-columns">
    <% @pokemons.each do |pokemon| %>
    <div class="card" style="width: 18rem;">
      <h5 class="card-title text-center"><%= pokemon.name %></h5>

      <div class="card-body">
        <% if pokemon.photo.attached?%>
        <%= cl_image_tag pokemon.photo.key, class:"card-img-top" %>
        <%end%>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Element : <%= pokemon.element %></li>
        <li class="list-group-item">Attack Points : <%= pokemon.attack %></li>
        <li class="list-group-item">Life Points : <%= pokemon.life %></li>
        <li class="list-group-item">Location : <%= pokemon.location %></li>
      </ul>
      <div class="card-body">
        <%= link_to 'Show', pokemon , class: 'btn btn-primary' %>
      </div>
    </div>
    <% end %>
  </div>
  <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/pokemons/edit.html.erb
<h1>EDIT</h1>
<div class="container">
  <%= simple_form_for(@pokemon) do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :element %>
  <%= f.input :life %>
  <%= f.input :attack %>
  <%= f.input :photo, as: :file%>
  <%= f.button :submit, class: 'btn btn-primary'  %>
  <% end %>

  <%= link_to 'Show', @pokemon, class: 'btn btn-primary' %> |
  <%= link_to 'Back', pokemons_path, class: 'btn btn-primary' %>
</div>

app/views/pokemons/index.html.erb
<h1>My Pokemons</h1>
<div class="container">
  <div class="card-columns">
    <% @pokemons.each do |pokemon| %>
    <div class="card" style="width: 18rem;">
      <h5 class="card-title text-center"><%= pokemon.name %></h5>

      <div class="card-body">
        <% if pokemon.photo.attached?%>
        <%= cl_image_tag pokemon.photo.key, class:"card-img-top" %>
        <%end%>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Element : <%= pokemon.element %></li>
        <li class="list-group-item">Attack Points : <%= pokemon.attack %></li>
        <li class="list-group-item">Life Points : <%= pokemon.life %></li>
        <li class="list-group-item">Location : <%= pokemon.location %></li>
      </ul>
      <div class="card-body">
        <%= link_to 'Show', pokemon , class: 'btn btn-primary' %>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/pokemons/new.html.erb
<h1>NEW</h1>

<div class="container">
  <%= simple_form_for(@pokemon) do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :element %>
  <%= f.input :life %>
  <%= f.input :attack %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary'  %>
  <% end %>

  <%= link_to 'Back', pokemons_path, class: 'btn btn-primary'  %>
</div>

app/views/pokemons/show.html.erb
<h1> SHOW </h1>
<div class="container">
  <div class="card mx-auto" style="width: 18rem; ">
    <h5 class="card-title text-center" style="margin-top: 8px"><%= @pokemon.name %></h5>

    <div class="card-body">
      <% if @pokemon.photo.attached? %>
      <%= cl_image_tag @pokemon.photo.key, class:"card-img-top" %>
    </div>
    <%end%>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Element : <%= @pokemon.element %></li>
      <li class="list-group-item">Attack Points : <%= @pokemon.attack %> <i class="fas fa-khanda"></i></li>
      <li class="list-group-item">Life Points : <%= @pokemon.life %><i class="fas fa-heart"></i></li>
      <li class="list-group-item">Location : <%= @pokemon.location %> <i class="fas fa-map-marker-alt"></i></li>
    </ul>
    <div class="card-body mx-auto">
      <%= link_to 'Recruit', new_pokemon_deck_path(@pokemon), class: 'btn btn-primary' %> |
      <%= link_to 'Back', pokemons_path, class: 'btn btn-primary'  %>
    </div>
    <div class="card-footer mx-auto">
      <% if user_signed_in? && current_user.eql?(@pokemon.user) %>
      <%= link_to 'Edit', edit_pokemon_path(@pokemon), class: 'btn btn-primary' %>
      <%= link_to "Delete", pokemon_path(@pokemon), method: :delete, class:"btn btn-primary", data: {confirm: "Are you sure"} %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <%= form_tag (controller_name == 'pages' && action_name == 'home') ? root_path : pokemons_path , method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a pokemon"%>
      </li>
      <li class="nav-item"><%= submit_tag "Search", class: 'btn btn-outline-dark' %></li>
      <% end %>
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to 'My Army', decks_path ,class: 'btn btn-outline-dark'%>
      </li>
      <li class="nav-item active">
        <%= link_to 'My Pokemons', pokemons_path ,class: 'btn btn-outline-dark'%>
      </li>
      <li class="nav-item active">
        <%= link_to 'My Battles', battle_path ,class: 'btn btn-outline-dark'%>
      </li>
      <li class="nav-item active">
        <%= link_to 'Add Pokemon', new_pokemon_path ,class: 'btn btn-outline-dark'%>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>